name: Merge and Resolve conflicts for Open PRs

on:
  push:
    branches:
      - main  
permissions:
  contents: write
  pull-requests: read
jobs:
  rebase-with-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:  
          token: ${{  secrets.GITHUB_TOKEN  }} 

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Fetch latest main branch
        run: |
          git fetch origin main
      # Get list of open PRs
      - name: Get list of open PRs
        id: pr_list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
          echo "::set-output name=prs::$prs"
          echo "$prs"

      - name: Rebase remaining PRs onto main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --json number,headRefName)
      
          # Loop through each open PR and rebase
          echo "$prs" | jq -c '.[]' | while IFS= read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            pr_branch=$(echo "$pr" | jq -r '.headRefName')
      
            if [ -z "$pr_branch" ]; then
              echo "::error::Skipping PR #$pr_number because branch name is empty."
              continue
            fi
      
            echo "Rebasing PR #$pr_number ($pr_branch) onto main branch..."
      
            git fetch origin pull/$pr_number/head:pr-$pr_number
            git checkout main
            git merge --no-ff pr-$pr_number || echo "Merge conflicts detected for PR #$pr_number: $pr_branch

            #if merge conflicts occur handle the conflicts automatically 
            if [ $? -ne 0 ]; then
              echo "Merge conflict detected for PR #$pr_number: $pr_branch
              git merge --strategy-option ours || echo "Merge resolution failed for PR #$pr_number
              git add .
              # git commit -m "Resolved conflicts for PR #$pr_number"
            fi

            #push the changes in main branch
            git push origin main
          done
      - name: Final push to main
        run: |
          git push origin main
