name: Rebase PR with Main on Push

on:
  push:
    branches:
      - main  
permissions:
  contents: write
  pull-requests: read
jobs:
  rebase-with-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch latest main branch
        run: |
          git fetch origin main

      - name: Rebase the PR branch onto main
        run: |
          git checkout ${{ github.head_ref }}
          git rebase origin/main

      - name: Check for rebase conflicts
        run: |
          if git diff --quiet; then
            echo "No conflicts detected during rebase."
          else
            echo "Conflicts detected during rebase! Resolving conflicts..."
            # Automatically resolve conflicts by keeping changes from the PR 
            git rebase --strategy=recursive --strategy-option=ours origin/main || echo "Automatic rebase failed. Conflicts need manual resolution."
            git add .
            git rebase --continue
          fi

      - name: Push changes back to the PR branch
        run: |
          git push --force-with-lease origin ${{ github.head_ref }}

